create database mydatabase;
use mydatabase;
select * from customer;
 -- Q1. What is the total revenue generated by male vs. female customers?
 select gender,sum(purchase_amount) as revenue
 from customer
 group by gender;
 
 -- Q2. Which customers used a discount but still spent more than the average purchase amount? 
 select customer_id,purchase_amount 
 from customer
 where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);
 
 -- Q3. Which are the top 5 products with the highest average review rating?
 
 SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

 
 -- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
 select shipping_type,round(avg(purchase_amount),2) as 'Average purchase amount'
 from customer 
 where shipping_type in('Express','Standard')
 group by shipping_type;
 
 -- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status ,count(customer_id) as total_customers ,avg(purchase_amount) as avg_spend,sum(purchase_amount) as total_revenue
from customer
where subscription_status in ('Yes','No')
group by subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
	Round((sum(case when discount_applied = 'Yes' THEN 1 else 0 end)*100.0) / count(*) ,2) as discount_purchase
    from customer
    group by item_purchased
    order by discount_purchase desc
    limit 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
        select customer_id,previous_purchases ,
		case when  previous_purchases = 1 then 'New' 
		when  previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal' end as customer_segment
        from customer)
select customer_segment,count(*) as number_of_customer
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with cte as(
	select category,
		item_purchased,
        count(customer_id) as total_orders,
        row_number() over(partition by category order by count(customer_id) desc ) as item_rank
        from customer
        group by category,item_purchased
        )
        select item_rank,category,item_purchased,total_orders
        from cte
        where item_rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_customer
from customer
where previous_purchases > 5 
group by subscription_status ;

-- Q10. What is the revenue contribution of each age group? 
select age_group ,sum(purchase_amount) as revenue 
from customer 
group by age_group
order by revenue desc;